### ISSUE TITLE
How to encode proteins in the PDBbind task?

### ISSUE THREAD

**Issue by fanxiaoyu0** [lsj2408/Transformer-M#3]
Very enlightening work. Congratulations on your great achievements in the OGB Challenge! In addition, I noticed that you have made fine-tuning on the PDBbind dataset. How should you encode the protein information? Because proteins usually contain more heavy atoms, do you directly use Transformer-M to encode proteins?

**Comment by 1874Mercury** [comment]
Also looking forward to the answer to this question...

**Comment by lsj2408** [comment]
It is a good catch! For the PDBBind task, each data instance is a protein-ligand complex. Since the size of a protein is much larger
than that of a ligand, each protein-ligand complex only contains the protein atoms around the ligand. Thus, the model receives the complex as input and predicts its binding affinity.
